server:
  port: xxx
spring:
  application:
    name: tdbj
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxx
    username: xxx
    password: xxx
  redis:
    host: xxx
    port: xxx
    password: xxx
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.tdbj.entity
logging:
  level:
    com.hmdp: debug